#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "coin"
name = "Coin"
description.en = "Member dashboard for non profit isp"
description.fr = "Outil pour un Internet Neutre"

version = "20240914~ynh1"

maintainers = ["ljf", "aleks"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://code.ffdn.org/FFDN/coin"
code = "https://code.ffdn.org/ffdn/coin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.email]
    ask.en = "Choose email were send notification"
    ask.fr = "Choisissez l'email vers lequel envoyer les notifications"
    type = "string"
    example = "admin@example.tld"

    [install.isp_name]
    ask.en = "Enter your ISP name"
    ask.fr = "Indiquez le nom de votre FAI"
    type = "string"
    example = "My ISP"

    [install.isp_site]
    ask.en = "Enter the address of your ISP website"
    ask.fr = "Saisissez l'adresse du site web de votre FAI"
    type = "string"
    example = "https://www.exemple.tld"

[resources]
    [resources.sources.main]
    url = "https://code.ffdn.org/ffdn/coin/-/archive/6986ba8.tar.gz"
    sha256 = "2cd45f2c62d238ee543d89a7355be03ed16c02b2df292ce554ba27499e5a66a0"
    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"

    [resources.apt]
    packages = ["gunicorn",
        "python3", "python3-venv", "libsasl2-dev", "libjpeg-dev", "libxml2-dev", "libxslt1-dev", "libpango1.0-0",
        "postgresql", "postgresql-contrib", "libpq-dev", "postgresql-server-dev-all"]

    [resources.database]
    type = "postgresql"
