test_format = 1.0

[default]
    #----------------------------
    # Default args to use for install
    # -------------------------------

        args.isp_name="ARN"
        args.isp_site="https://arn-fai.net"