command = '/var/www/__YNH_APP_INSTANCE_NAME__/venv/bin/gunicorn'
pythonpath = '/var/www/__YNH_APP_INSTANCE_NAME__'
workers = 4
user = '__YNH_APP_INSTANCE_NAME__'
bind = 'unix:/var/www/__YNH_APP_INSTANCE_NAME__/sock'
pid = '/run/gunicorn/__YNH_APP_INSTANCE_NAME__-pid'
errorlog = '/var/log/__YNH_APP_INSTANCE_NAME__/error.log'
accesslog = '/var/log/__YNH_APP_INSTANCE_NAME__/access.log'
access_log_format = '%({X-Real-IP}i)s %({X-Forwarded-For}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
loglevel = 'warning'
capture_output = True
