#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {
  try_files $uri @__APP__;
}

location __PATH__/protected/ {
  internal;
  alias __INSTALL_DIR__/smedia/;
}

location __PATH__/media/  {
  alias __INSTALL_DIR__/media/;
}

location __PATH__/static/ {
  alias __INSTALL_DIR__/static/;
}

location __PATH__/assets/ {
  alias __INSTALL_DIR__/static/;
}

location @__APP__ {
  proxy_pass http://unix:__INSTALL_DIR__/sock;
  include proxy_params_no_auth;
}
