#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_systemctl --service=$app --action="stop"

ynh_config_change_url_nginx

ynh_config_add --jinja --template=local.py.j2 --destination="$install_dir/coin/settings_local.py"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/coin/settings_local.py"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app "$install_dir/coin/settings_local.py"

ynh_systemctl --service=$app --action="start"

ynh_script_progression "Change of URL completed for $app"
