#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

ynh_change_url_nginx_config

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

ynh_script_progression --message="Change of URL completed for $app" --last
