#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_python
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

export secret=$(ynh_string_random 24)

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
#REMOVEME? ynh_script_progression --message="Validating installation parameters..." --weight=1

#export install_dir=/opt/$app
#REMOVEME? test ! -e "$install_dir" || ynh_die --message="This path already contains a folder"

# Register (book) web path
#REMOVEME? ynh_webpath_register --app=$app --domain=$domain --path=$path

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
#REMOVEME? ynh_script_progression --message="Storing installation settings..." --weight=1

#ynh_app_setting_set --app=$app --key=email --value=$email
#ynh_app_setting_set --app=$app --key=isp_name --value=$isp_name
#ynh_app_setting_set --app=$app --key=isp_site --value=$isp_site

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Installing dependencies..." --weight=1

ynh_install_python --python_version=$python_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# PYTHON DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Installing more dependencies..." --weight=1

pushd "$install_dir"
	ynh_use_python
	ynh_exec_warn_less $ynh_pip install --upgrade pip
	ynh_exec_warn_less $ynh_pip install gunicorn
	echo "django-auth-ldap<1.4" >> $install_dir/requirements.txt
	ynh_exec_warn_less $ynh_pip install -r $install_dir/requirements.txt
popd

#=================================================
# CONFIGURATION DJANGO
#=================================================
ynh_script_progression --message="Configuring application..." --weight=1

export prefix="${path#"/"}/"
prefix=${prefix%"/"}
ynh_render_template ../conf/local.py.j2 "$install_dir/coin/settings_local.py"
ynh_store_file_checksum --file="$install_dir/coin/settings_local.py"

#=================================================
# SERVE STATIC FILES IN PRODUCTION MODE
#=================================================

ln -s $install_dir/$app/static $install_dir/static

#=================================================
# SETUP DATABASE
#=================================================

# Set permissions
chown -R $app:www-data $install_dir

pushd $install_dir
	ynh_exec_warn_less $ynh_python manage.py migrate --noinput
	ynh_exec_warn_less $ynh_python manage.py collectstatic --noinput
popd

# Set permissions to directory
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# CONFIGURE LOG DIR
#=================================================

mkdir -p /var/log/$app
chown -R $app /var/log/$app
chown -R $app:www-data "/var/log/$app"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="gunicorn_config.py" --destination="$install_dir/gunicorn_config.py"

chown $app:www-data "$install_dir/gunicorn_config.py"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description "$app daemon" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
