#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX web server configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_psql_db_shell  < "./db.sql"

#=================================================
# PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling venv..."

ynh_safe_rm "${install_dir}/venv"
pushd "$install_dir"
    python3 -m venv venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install gunicorn
	#echo "django-auth-ldap<1.4" >> $install_dir/requirements.txt
    venv/bin/pip install -r requirements.txt
popd

#=================================================
# CONFIGURE LOG DIR
#=================================================

mkdir -p /var/log/"$app"
chown -R "$app":"$app" /var/log/"$app"
chmod -R 750 "/var/log/$app"

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring $app's systemd service..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app".service --quiet

yunohost service add "$app" --description "$app daemon" --log="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
